version: '3'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - docker_default
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./provisioning/grafana:/etc/grafana/provisioning
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./provisioning/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - docker_default
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOBASE=${GOPATH}
    networks:
      - public
      - docker_default
    environment:
      - AIS_NODE_ROLE=proxy
      - AIS_NO_DISK_IO=${AIS_NO_DISK_IO}
      - PORT=${PORT}
      - AIS_PRIMARY_URL=http://${PRIMARY_IP}:${PORT}
      - AIS_BACKEND_PROVIDERS=${AIS_BACKEND_PROVIDERS}
    env_file:
      - /tmp/docker_ais/tmp.env
      - /tmp/docker_ais/aws.env
    user: ${UID:-1000}
    volumes:
      - ${GOPATH}/src:${GOPATH}/src
      - /tmp/ais/${CLUSTER:-0}:/tmp/ais
  target:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOBASE=${GOPATH}
    networks:
      - public
      - docker_default
    environment:
      - AIS_NODE_ROLE=target
      - AIS_NO_DISK_IO=${AIS_NO_DISK_IO}
      - PORT=${PORT}
      - AIS_PRIMARY_URL=http://${PRIMARY_IP}:${PORT}
      - AIS_BACKEND_PROVIDERS=${AIS_BACKEND_PROVIDERS}
    env_file:
      - /tmp/docker_ais/tmp.env
      - /tmp/docker_ais/aws.env
    user: ${UID:-1000}
    volumes:
      - ${GOPATH}/src:${GOPATH}/src
      - /tmp/ais/${CLUSTER:-0}:/tmp/ais
networks:
  docker_default:
    external: true
  public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${PUB_SUBNET:-172.5.0.0/24}
